SELECT ip, COUNT(*) AS invalid_count
FROM logs
WHERE 
(CAST(SUBSTRING_INDEX(ip, '.', 1) AS UNSIGNED) > 255 OR
CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(ip, '.', 2), '.', -1) AS UNSIGNED) > 255 OR
CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(ip, '.', 3), '.', -1) AS UNSIGNED) > 255 OR
CAST(SUBSTRING_INDEX(ip, '.', -1) AS UNSIGNED) > 255)
OR REGEXP_LIKE(ip, '\\b0[0-9]+\\b')
OR (LENGTH(ip) - LENGTH(REPLACE(ip, '.', '')) != 3)
GROUP BY ip
ORDER BY invalid_count DESC, ip DESC;
